# GitHub Pages Jekyll Configuration
title: "2025 Plans - Flutter E-commerce Development"
description: "Comprehensive Flutter e-commerce development plans and guides"
baseurl: "/2025-Plans"
url: "https://zahraah-dev.github.io"

# Build settings for GitHub Pages
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minimal

# GitHub Pages plugins (built-in)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/workflows/
  - *.sh
  - temp_*

# Site settings
lang: ar
direction: rtl

# SEO
author: "Zahraah Dev"
email: "dev@zahraah.com"

# Social links
github_username: zahraah-dev
